#!/usr/bin/env bash
# script to install and setup nginx

function install_nginx(){
    sudo apt-get update
    sudo apt-get -y install nginx
    echo 'Hello World!' > /var/www/html/index.html
    service nginx start

}
install_nginx;
