#!/usr/bin/env bash
# Highlander

# Function to handle the SIGTERM signal
handle_sigterm() {
  echo "I am invincible!!!"
  exit 0
}

# Trap the SIGTERM signal and call the handle_sigterm function
trap 'handle_sigterm' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
