#!/usr/bin/env bash
# this script displays numbers from 1 to 100.
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number

for i in $(seq 1 100);
do
    if [ $((i % 3)) -eq 0 ]; then
	echo "Fizz"
    elif [ $((i % 5)) -eq 0 ]; then
	echo "Buzz"
    elif [ $((i % 15)) -eq 0 ]; then
	echo "FizzBuzz"
    else
	echo "$i"
    fi
done
